name:                codewars
version:             0.1.0.0
github:              "BoeingX/codewars"
license:             BSD3
author:              "BoeingX"
maintainer:          "12154983+BoeingX@users.noreply.github.com"
copyright:           "2019 BoeingX"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/codewars#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- regex-pcre
- random

build-tools:
- alex
- happy

library:
  source-dirs: src

executables:
  codewars-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codewars

tests:
  codewars-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codewars
    - hspec
    - HUnit
    - QuickCheck
